config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  get '/me', to: 'users#me'
  resources :users, only: %i[show update]
  resources :events, only: %i[index show create new] do
    resources :messages, only: :create
    resources :registrations, only: :create
  end
  namespace :my do
    resources :events, only: %i[index]
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/event.rb
class Event < ApplicationRecord
  include PgSearch::Model
  EXPERIENCE = ["Newbie", "Beginner", "Intermidiate", "Professional"]
  belongs_to :game
  belongs_to :venue
  belongs_to :user
  has_many :registrations, dependent: :destroy
  has_many :users, through: :registrations
  has_many :messages

  validates :title, presence: true
  validates :spots, presence: true
  validates :date, presence: true

  pg_search_scope :city_search, against: [:title], associated_against:
  { venue: [:address] }

  def participants
    [user] + users
  end

  def time_type
    if date.today?
      time_type = 'today'
    elsif date.to_date == Date.tomorrow
      time_type = 'tomorrow'
    elsif (date.to_date.cweek == Date.today.cweek) && (date.friday? || date.saturday? || date.sunday?)
      time_type = 'weekend'
    elsif date.to_date.cweek == Date.today.cweek
      time_type = 'week'
    end
    time_type
  end
end

app/models/game.rb
class Game < ApplicationRecord
  has_many :events
  validates :name, presence: true
  validates :game_type, presence: true
  has_one_attached :photo
end

app/models/gender.rb
class Gender < ApplicationRecord
end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :event
  belongs_to :user

  validates :content, presence: true, length: { minimum: 5 }
end

app/models/registration.rb
class Registration < ApplicationRecord
  belongs_to :event
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  belongs_to :gender

  has_many :events
  has_many :registrations
  has_many :participations, through: :registrations, source: :event
  has_many :messages
  has_one_attached :photo

  geocoded_by :address
  after_validation :geocode, if: :will_save_change_to_address?
end

app/models/venue.rb
class Venue < ApplicationRecord
  has_many :events
  validates :address, presence: true
  validates :name, presence: true
  validates :description, presence: true
  geocoded_by :address
  after_validation :geocode, if: :will_save_change_to_address?
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?

  include Pundit

  # Pundit: white-list approach.
  after_action :verify_authorized, except: :index, unless: :skip_pundit?
  after_action :verify_policy_scoped, only: :index, unless: :skip_pundit?

  # Uncomment when you *really understand* Pundit!
  # rescue_from Pundit::NotAuthorizedError, with: :user_not_authorized
  def user_not_authorized
    flash[:alert] = "You are not authorized to perform this action."
    redirect_to(root_path)
  end

  def default_url_options
    { host: ENV["DOMAIN"] || "localhost:3000" }
  end

  private

  def configure_permitted_parameters

    devise_parameter_sanitizer.permit(:sign_up, keys: %i[nickname age gender_id])
  end

  def skip_pundit?
    devise_controller? || params[:controller] =~ /(^(rails_)?admin)|(^pages$)/
  end

end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  skip_before_action :authenticate_user!, only: %i[index]
  def index
    @query = params['query']
    @events = Event.city_search(@query) if @query.present?
    if @events
      @events = policy_scope(@events)
    else
      @events = policy_scope(Event)
    end
    @markers = @events.map do |event|
      {
        lat: event.venue.latitude,
        lng: event.venue.longitude,
        gameType: event.game.game_type,
        timeType: event.time_type,
        infoWindow: render_to_string(partial: "events/info_window", locals: { event: event })
      }
    end
  end

  def show
    @message = Message.new
    @event = Event.find(params[:id])
    authorize @event
  end

  def new
    @event = Event.new
    authorize @event
  end

  def create
    @event = Event.new(event_params)
    @event.user = current_user
    authorize @event
    if @event.save
      redirect_to my_events_path
    else
      flash[:danger] = @event.errors.full_messages.join(', ')
      render :new
    end
  end

  private

  def event_params
    params.require(:event).permit(:title, :date, :spots, :description, :experience_level, :min_age, :max_age, :game_id, :venue_id)
  end
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  def create
    @event = Event.find(params[:event_id])
    @message = Message.new(message_params)
    @message.event = @event
    @message.user = current_user
    authorize @message
    if @message.save
      EventChannel.broadcast_to(
        @event,
        render_to_string(partial: "message", locals: { message: @message })
      )
      respond_to do |f|
        f.html { redirect_to event_path(@event, anchor: "message-#{@message.id}") }
        f.js { head :no_content }
      end
    else
      render "events/show"
    end
  end

  def message_params
    params.require(:message).permit(:content)
  end

end

app/controllers/my/events_controller.rb
class My::EventsController < ApplicationController

  def index
    @events = policy_scope([:my, Event.where(user: current_user)])
    @participations = policy_scope([:my, Registration.where(user: current_user)])
    group_events(@events, @participations)
    @events = @all_events
    @message = Message.new
  end

  private

  def group_events(events1, events2)
    @all_events = []
    events1.each do |event|
      @all_events <<  event
    end
    events2.each do |par|
      @all_events <<  par.event
    end
    @all_events
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: [ :home ]

  def home
  end
end

app/controllers/registrations_controller.rb
class RegistrationsController < ApplicationController
  def create
    @registration = Registration.new(registration_params)
    @registration.user = current_user
    authorize @registration
    if @registration.save
      redirect_to my_events_path
    else
      flash[:alert] = 'You where not able to sign up for the event!'
    end
  end

  def registration_params
    params.permit(:event_id)
  end
end

app/controllers/user/events_controller.rb
class User::EventsController < ApplicationController
  def new
    @event = Event.new
    authorize [:user, @event]
  end
  def create
    @event = Event.new(event_params)
    @event.user = current_user
    authorize [:user, @event]
    if @event.save
      redirect_to user_events_path
    else
      flash[:danger] = @event.errors.full_messages.join(', ')
      render :new
    end
  end

  def event_params
    params.require(:event).permit(:title, :date, :spots, :description, :experience_level, :min_age, :max_age)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!
  def me
    @user = current_user
    authorize @user
  end

  # def show; end

  def show
    @user = User.find(params[:id])
    if user_signed_in?
      authorize @user
    end
  end


  def update
    @user = User.find(params[:id])
    authorize @user
    if @user.update(user_params)
      redirect_to(me_path, notice: 'Your user profile was updated')
    else
      redirect_to(me_path, alert: 'Something went wrong, user profile not updated')
    end
  end

  def user_params
    params.require(:user).permit(:name, :email, :photo, :password, :gender_id, :nickname, :preferred_games, :address, :age)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/meta_tags_helper.rb
module MetaTagsHelper
  def meta_title
    content_for?(:meta_title) ? content_for(:meta_title) : DEFAULT_META["meta_title"]
  end

  def meta_description
    content_for?(:meta_description) ? content_for(:meta_description) : DEFAULT_META["meta_description"]
  end

  def meta_image
    meta_image = (content_for?(:meta_image) ? content_for(:meta_image) : DEFAULT_META["meta_image"])
    # little twist to make it work equally with an asset or a url
    meta_image.starts_with?("http") ? meta_image : image_url(meta_image)
  end
end

app/views/events/_info_window.html.erb
  <h3 class="info-text"><%= event.venue.name %></h3>
  <p class="info-text-p"><%= event.venue.description %></p>
  <p class="info-text-p"><%= event.venue.address %></p>

app/views/events/index.html.erb
<div class="container-e pl-5 pr-5" data-controller="events" data-events-game-type-filter="" data-events-time-type-filter="">
  <div class="row">
    <div class="col-sm-12 col-md-6 cold-lg-6" data-target="events.events" style="padding: 10px;">
      <h1 style="color: rgb(8,146,208);">All events</h1>
      <%= simple_form_for("", method: :get, url: events_path) do |f| %>
      <div class="form-group search-box">
        <%= f.input :query, label: false, :input_html => { :class => 'form-control search-txt' }, placeholder: 'Search for city..' %>
        <button name="button" type="submit" class="search-btn"><i class="fas fa-search"></i></button>
      </div>
      <% end  %>
      <div class="filtersss d-flex justify-content-between">
        <div class="gametypee my-2">
             <h3>Game type</h3>
             <input class="checkbox-budget" type="checkbox" name="game-type" id="budget-1" data-action="click->events#filterGameType" data-game-type="strategy">
                <label class="for-checkbox-budget" for="budget-1">
                  <span >Strategy</span>
                </label>
                <input class="checkbox-budget" type="checkbox" name="game-type" id="budget-2" data-action="click->events#filterGameType" data-game-type="fun">
                <label class="for-checkbox-budget" for="budget-2">
                  <span >Fun</span>
                </label><!--
                --><input class="checkbox-budget" type="checkbox" name="game-type" id="budget-3" data-action="click->events#filterGameType" data-game-type="trivia">
                <label class="for-checkbox-budget" for="budget-3">
                  <span >Trivia</span>
                </label><!--
                --><input class="checkbox-budget" type="checkbox" name="game-type" id="budget-4" data-action="click->events#filterGameType" data-game-type="adventure">
                <label class="for-checkbox-budget" for="budget-4">
                  <span >Adventure</span>
                </label>
            </div>
            <div class="dateee my-2">
            <h3>Date</h3>
             <input class="checkbox-budget" type="checkbox" name="game-time" id="budget-5" data-action="click->events#filterTimeType" data-target="events.today" data-time-type="today">
                <label class="for-checkbox-budget" for="budget-5">
                  <span>Today</span>
                </label><!--
                --><input class="checkbox-budget" type="checkbox" name="game-time" id="budget-6" data-action="click->events#filterTimeType" data-target="events.tomorrow" data-time-type="tomorrow">
                <label class="for-checkbox-budget" for="budget-6">
                  <span>Tomorrow</span>
                </label><!--
                --><input class="checkbox-budget" type="checkbox" name="game-time" id="budget-7" data-action="click->events#filterTimeType" data-target="events.weekend" data-time-type="weekend">
                <label class="for-checkbox-budget" for="budget-7">
                  <span>This weekend</span>
                </label><!--
                --><input class="checkbox-budget" type="checkbox" name="game-time" id="budget-8" data-action="click->events#filterTimeType" data-time-type="week">
                <label class="for-checkbox-budget" for="budget-8">
                  <span>This week</span>
                </label>
          </div>
      </div>
      <%= render "shared/card" %>
    </div>
    <div class="col-sm-12 col-md-6 cold-lg-6">
      <div class="sticky-top">
        <div class="mapp sticky-top" id="map" style="width: 100%; height: 1000px;" data-markers="<%= @markers.to_json %>" data-mapbox-api-key="<%= ENV['MAPBOX_API_KEY'] %>"></div>
      </div>
    </div>
  </div>
</div>

app/views/events/new.html.erb
<div class="wrapper rapas">
  <div class="back">

  </div>

<div class="formike d-flex align-items-left">
  <div class="container left">
    <div class="row justify-content-center">
      <div class="col-8">
        <div class="form text-white p-4">
          <h1 class="text-center">Add new event</h1>
          <%= simple_form_for @event do |f| %>
           <%= f.error_notification %>
           <%= f.input :title, placeholder: "e.g. Chess duel" %>
           <div class="row">
            <div class="col-4">
              <%= f.association :game, required: true, prompt: :translate  %>
            </div>
            <div class="col-4">
              <%= f.association :venue, required: true, prompt: :translate  %>
            </div>
            <div class="col-4">
              <%= f.input :spots, placeholder: "e.g. 2" %>
            </div>
          </div>
           <div class="row">
            <div class="col-4">
               <%= f.input :min_age, placeholder: "25" %>
            </div>
            <div class="col-4">
               <%= f.input :max_age, placeholder: "30" %>
            </div>
            <div class="col-4" style="line-height: 32px;">
              Choose date and time*<br>
               <%= f.text_field :date, data: { behavior: "flatpickr" }, label: 'Choose date and time', placeholder: 'Date and Time', class: "form-control" %>
            </div>
          </div>
           <%= f.input :experience_level, collection: Event::EXPERIENCE, prompt: :translate %>
           <%= f.input :description, placeholder: "e.g Just looking for someone to play game of chess" %>
           <%= f.submit class: "btn btn-primary btn-lg btn-block", style: "border-radius:10px;" %>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>
</div>

app/views/events/show.html.erb
<div class="bannerr d-flex justify-content-center align-items-center">
</div>
<div class="wrapper">
  <div class="bck d-flex justify-content-center align-items-center">
  <div class="ttt text-center">
      <h1 class="display-1 gg text-primary">Join an event</h1>
  </div>
    <div class="container dd">
        <div class="row">
          <div class="col-12">
            <div class="card pin mb-3" style="max-width: 1500px;border-radius: 15px;max-height:600px;">
              <div class="row no-gutters">
                <div class="col-md-4">
                  <img src="https://cdn.cnn.com/cnnnext/dam/assets/200421100635-underscored-best-board-games-lead-live-video.jpg" alt="" class="bd-placeholder-img ii" width="100%" height="250" border-radius="10">
                </div>
                <div class="col-md-8">
                  <div class="card-body ccc d-flex justify-content-between">
                    <div>
                      <h5 class="card-title"><%= @event.title %></h5>
                      <p class="card-text" style="max-width: 550px;"><%= @event.description %></p>
                      <p >Spots left <%= @event.spots - @event.registrations.count %></p>
                    </div>
                    <div class="d-flex">
                      <time datetime="@event.date.strftime(%d %m %Y')" class="icon">
                        <em><%= @event.date.strftime("%A") %></em>
                        <strong><%= @event.date.strftime("%B")%></strong>
                        <span><%= (@event.date + 6).strftime('%y') %></span>
                      </time>
                    </div>
                    <% if (@event.registrations.pluck(:user_id).include?(current_user.id)) || (@event.spots < @event.registrations.count) %>
                    <div class="text-align-left bottom-right">
                      <button type="button" class="btn btn-secondary btn-lg" disabled>Join event</button>
                    </div>
                    <% else %>
                    <div class="text-align-left">
                      <%= link_to "Join event", event_registrations_path(@event.id), method: :post, class: "btn btn-lg btn-primary bottom-right" %>
                    </div>
                    <% end %>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
        <div class="row">
          <div class="col-4">
            <div class="card pin" style="width: 340px; border-radius: 15px;max-height:350px;">
              <img class="bd-placeholder-img ii" src="https://www.noblecollection.com/Galleria/1/PRP-JU-3531-Large.jpg" alt="Card image cap" width="100%" height="250" border-radius="10">
            </div>
          </div>
          <div class="col-8">
            <div class="card pin mb-3" style="max-width: 740px;border-radius: 15px;max-height:350px;">
              <div class="row no-gutters">
                <div class="col-md-4">
                  <img src="https://texashillcountry.com/wp-content/uploads/11836712_738774506250645_1580314188759681459_n-680x390.jpg" alt="img" class="bd-placeholder-img ii" width="100%" height="250" border-radius="10">
                </div>
                <div class="col-md-8">
                  <div class="card-body">
                    <h5 class="card-title"><%= @event.venue.name %></h5>
                    <p class="card-text"><%= @event.venue.address %></p>
                    <p class="card-text"><%= @event.venue.description %></p>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>


    <i class="fas fa-dice"></i>
      </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= meta_title %></title>
    <meta name="description" content="<%= meta_description %>">

    <!-- Facebook Open Graph data -->
    <meta property="og:title" content="<%= meta_title %>" />
    <meta property="og:type" content="website" />
    <meta property="og:url" content="<%= request.original_url %>" />
    <meta property="og:image" content="<%= meta_image %>" />
    <meta property="og:description" content="<%= meta_description %>" />
    <meta property="og:site_name" content="<%= meta_title %>" />

    <!-- Twitter Card data -->
    <meta name="twitter:card" content="summary_large_image">
    <meta name="twitter:site" content="<%= DEFAULT_META["twitter_account"] %>">
    <meta name="twitter:title" content="<%= meta_title %>">
    <meta name="twitter:description" content="<%= meta_description %>">
    <meta name="twitter:creator" content="<%= DEFAULT_META["twitter_account"] %>">
    <meta name="twitter:image:src" content="<%= meta_image %>">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= favicon_link_tag %>

    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload', defer: true %>
  </head>

  <body>
     <div class="page-container">
        <div class="page-content">
          <%= render 'shared/navbar' %>
          <%= render 'shared/flashes' %>
          <%= yield %>
        </div>
        <div class="page-footer">
          <%= render 'shared/footer' %>
        </div>

      </div>
  </body>
</html>

app/views/messages/_message.html.erb
<div class="chat-log" >
  <div class="chat-message" id="message-<%= message.id %>" data-message-userid="<%= message.user.id %>">
        <p class="chat-message__text chat-left hidden-chat"><em><%= message.user.nickname.capitalize %></em><br><span class="hidden-chat-dots chat-left-stick "></span></span><%= message.content %><span class="message-timestamp-right"><%= time_ago_in_words(message.created_at)%> ago</span></p>
        <span class="chat-message__avatar-frame">
      <% if message.user.photo.attached? %>
      <%=  cl_image_tag message.user.photo.key, class: "chat-message__avatar", height: 50, width: 50, crop: :fill %>
      <% else %>
        <img src="https://media.kasperskydaily.com/wp-content/uploads/sites/85/2019/08/12075337/selfie-with-id-card-scam-featured.jpg" alt="" class='chat-message__avatar'>
      <% end %>
    </span>
    <p class="chat-message__text chat-right"><em><%= message.user.nickname.capitalize %>:</em><br><span class="hidden-chat-dots chat-right-stick"></span><%= message.content %><span class="message-timestamp-left"><%= time_ago_in_words(message.created_at)%> ago</span></p>
  </div>
</div>

app/views/pages/home.html.erb
<div class="banner text-center">
  <div class="row" style="height: 100%; width: 100%;">
    <div class="col-12 d-flex justify-content-center align-items-center" style="height: 100%; width: 100%;">
      <div>
        <h1 class="text-white disp">Step into board games with</h1>
        <h1 class="tittt display-1">let's play</h1>
        <p class="displ text-white text-bold">Join board game events. <br> Organise your own!</p>
        <div class="d-flex justify-content-between dded mt-4" style="width: 550px;">
          <%= link_to "events", events_path, class: "btn btn-primary ser-but btn-lg" %>
          <%= link_to "organise", new_event_path, class: "btn btn-primary ser-butt btn-lg" %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/shared/_card.html.erb
<% @events.each do |event| %>
<div class="event-card"
data-game-type="<%= event.game.game_type %>"
  data-time-type="<%= event.time_type %>"
  data-eventid="<%= event.id %>"
  data-hosting="<%= event.user == current_user %>">>
  <div class="d-flex top-event">
    <div class="imgevent">
      <%=  cl_image_tag event.game.photo.key, class: "img-event-repso", height: 300, width: 300, crop: :fill %>
    </div>
    <div class="eventinfo">
      <h2 class="eve-title-resp"> <%= event.title.truncate(20) %></h2>
      <p class="font-bold desc-event"><%= event.description.truncate(100) %></p>
      <p id="spots-l">Spots left <%= event.spots - event.registrations.count %> ! </p>
    </div>
    <div class="eventcalendar d-flex justify-content-center align-items-center">
      <time datetime="@event.date.strftime(%d %m %Y')" class="icon">
        <em><%= event.date.strftime("%A") %></em>
        <strong><%= event.date.strftime("%B")%></strong>
        <span><%= (event.date + 6).strftime('%e') %></span>
      </time>
    </div>
  </div>
  <div class="full d-flex justify-content-center align-items-center">
    <div class="borderis">
    </div>
  </div>
  <div class="d-flex bottom-event">
    <div class="d-flex created-event-by justify-content-center align-items-center">
       <% if event.user.photo.attached? %>
        <%=  cl_image_tag event.user.photo.key, class: "small-avatar mr-2", height: 50, width: 50, crop: :fill %>
        <% else %>
          <img src="https://media.kasperskydaily.com/wp-content/uploads/sites/85/2019/08/12075337/selfie-with-id-card-scam-featured.jpg" alt="" class='small-avatar'>
      <% end %>
       <div class="">
        <p>Created by </p>
        <p><%= event.user.nickname %></p>
      </div>
    </div>
    <div class="distance-to d-flex justify-content-left align-items-center">
      <div>
        <p><%= event.venue.name %>  <% if user_signed_in? && current_user.address.present? %></p>
        <p><%= (current_user.distance_to(event.venue.to_coordinates) * 1.35 ).round %> km  away <i class="fas fa-map-marker-alt"></i> <% end %></p>
      </div>
    </div>
    <div class="join-but d-flex justify-content-center align-items-center">
      <% if user_signed_in? && event.registrations.pluck(:user_id).include?(current_user.id) %>
        <div class="btn-event1">
          <button type="button" class="btn-gg btn-lg btn-disable" disabled>Registered!</button>
        </div>
        <% elsif user_signed_in? && event.user_id == current_user.id %>
        <div class="btn-event1">
          <button type="button" class="btn-gg btn-lg btn-disable" disabled>My event!</button>
        </div>
        <% elsif event.spots <= event.registrations.count %>
        <div class="btn-event1">
          <button type="button" class="btn-gg btn-lg btn-disable" disabled>Event full!</button>
        </div>
        <% else %>
        <div class="btn-event1">
          <%= link_to "Join event!", event_registrations_path(event.id), method: :post, class: "btn-gg btn btn-lg" %>
        </div>
        <% end %>
    </div>
  </div>
</div>
<% end %>

app/views/shared/_dashboard.html.erb
<div class=" py-3 pl-5 text-info"> <= Click card for refresh details below:</div>
<% @events.each do |event| %>
  <div class="row dashboardEvent" style="display:none;" data-eventID="<%= event.id %>">
    <div class="col-12 text-center pt-3 pb-5"><h2><%= event.title %></h2></div>
    <div class="col-12">
      <div class="row d-flex justify-content-center">
        <div class="col-5 text-center my-1"><h4 class="text-right">Game</h4></div>
        <div class="col-5 my-1"><h4><%= event.game.name %></h4></div>
        <div class="col-5 text-center my-1"><h4 class="text-right">Venue</h4></div>
        <div class="col-5 my-1"><h4><%= event.venue.name %>, <%= event.venue.address %></h4></div>
        <div class="col-5 text-center my-1"><h4 class="text-right">Date</h4></div>
        <div class="col-5 my-1"><h4><%= event.date.strftime("%^A %-d %^B %Y") %></h4></div>
        <div class="col-5 text-center my-1"><h4 class="text-right">Time</h4></div>
        <div class="col-5 my-1"><h4><%= event.date.strftime("%k:%M HRS") %></h4></div>
      </div>
    </div>
    <div class="col-12">
      <div class="text-center text-uppercase mt-5">
        <h4>participants</h4>
      </div>
      <div class="row d-flex justify-content-center mt-2">
        <div class="col-10 player-groups py-5 mb-5">
            <div class="row d-flex justify-content-center">
                <% event.participants.each do |participant| %>
                  <div class="col-5 plaque py-1">
                    <div class="row d-flex justify-content-center">
                      <div class="col-2 pl-3 pr-0"><%= cl_image_tag participant.photo.key, class: 'small-avatar' %></div>
                      <div class="col-8 nametag mb-0 d-flex align-items-center"><h6 class="mb-0"><%= link_to participant.nickname, user_path(participant) %></h6></div>
                    </div>
                  </div>
                <% end %>
            </div>
        </div>
      </div>
    </div>
<!--     <div class="col-12 text-center update-info">
      <p>Last update:</p>
      <p><span>3 Hrs ago... :</span> TimT joined</p>
    </div> -->
<!--     <div class="col-12 text-center d-flex justify-content-center mt-5">
      <button class="btn btn-primary">Edit Event</button>
    </div> -->
  </div>
  <% end %>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-background navbar-lewagon navbar-height">
  <%= link_to root_path, class: "navbar-brand" do %>
    <%= image_tag "LOGO.png", class: 'navbar-logo' %>
    <% end %>

  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>


  <div class="collapse navbar-collapse text-align-center" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto align-items-center">
      <% if user_signed_in? %>
        <h5>
        <li class="nav-item active">
          <%= link_to "Home", root_path, class: "btn btn-outline-primary btn-lg button-navbar mr-3" %>
        </li>
        </h5>
        <h5>
        <li class="nav-item active">
          <%= link_to "All events", events_path, class: "btn btn-outline-primary btn-lg button-navbar mr-3" %>
        </li>
        </h5>
        <h5>
        <li class="nav-item active">
          <%= link_to "Create event", new_event_path, class: "btn btn-outline-primary btn-lg button-navbar mr-3" %>
        </li>
      </h5>
        <h5>
        <li class="nav-item">
          <%= link_to "My events", my_events_path, class: "btn btn-outline-primary btn-lg button-navbar mr-4" %>
        </li>
      </h5>
        <li class="nav-item dropdown">
      <% if current_user.photo.attached? %>
      <% image_url = cloudinary_url(current_user.photo.key) %>
      <% else %>
      <% image_url = 'https://miro.medium.com/max/395/1*reXbWdk_3cew69RuAUbVzg.png' %>
      <% end %>
          <%= image_tag image_url, class: "avatar-square-navbar dropdown-toggle mt-1 navbar-pointer mr-2", id: "navbarDropdown", data: { toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
          <div class="dropdown-menu dropdown-menu-right" id="avatar-dropdown" aria-labelledby="navbarDropdown">
            <%= link_to "My profile", me_path, class: "dropdown-item navbar-dropdown-text" %>
            <%= link_to "Log out", destroy_user_session_path, method: :delete, class: "dropdown-item navbar-dropdown-text" %>
          </div>
        </li>
      <% else %>
      <h5>
        <li class="nav-item">
          <%= link_to "Login", new_user_session_path, class: "btn btn-outline-primary btn-lg button-navbar mr-4" %>
        </li>
      </h5>
      <% end %>
    </ul>
  </div>
</div>